version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: python -m unittest emp_management_test
      - run:
          name: Run integration tests
          command: python -m unittest emp_management_integtest.py
